name: Build and publish release
on:
  push:
    tags:
      - "v?[0-9].[0-9].[0-9]"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
            --repo "$GITHUB_REPOSITORY" \
            --title "Version ${tag#v}" \
            --notes-file "${GITHUB_WORKSPACE}/.github/release.md" \
            "${GITHUB_WORKSPACE}/primer.css"
