name: Build and test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: "*"
    tags-ignore:
      - "v?[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: clairelizbet/action-build@v1
      - uses: clairelizbet/action-test@v1
