name: Test and publish release
on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+"

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: clairelizbet/action-npm-install@v1

      - uses: clairelizbet/action-test@v1
        with:
          restore-build: false

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
            --repo "$GITHUB_REPOSITORY" \
            --title "Version ${tag#v}" \
            --notes-file "${GITHUB_WORKSPACE}/.github/release.md" \
            "${GITHUB_WORKSPACE}/primer.css"
