name: Test and publish release

on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+"

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: clairelizbet/action-npm-install@v1

      - uses: clairelizbet/action-test@v1
        with:
          restore-build: false

      - uses: clairelizbet/action-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            "${GITHUB_WORKSPACE}/primer.css"

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
